steps:
  - name: gcr.io/cloud-builders/docker
    args: ["build", "-t", "${_REGION}-docker.pkg.dev/$PROJECT_ID/${_REPOSITORY}/icc-erp:$COMMIT_SHA", "."]
  - name: gcr.io/cloud-builders/docker
    args: ["push", "${_REGION}-docker.pkg.dev/$PROJECT_ID/${_REPOSITORY}/icc-erp:$COMMIT_SHA"]
images:
  - "${_REGION}-docker.pkg.dev/$PROJECT_ID/${_REPOSITORY}/icc-erp:$COMMIT_SHA"
substitutions:
  _REGION: asia-south1
  _REPOSITORY: icc-erp
options:
  logging: CLOUD_LOGGING_ONLY
