"""Buddy overlap controls

Revision ID: 3d011a633fd7
Revises: 156ac146987b
Create Date: 2026-07-16 14:16:47.725517

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3d011a633fd7'
down_revision = '156ac146987b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('buddy_assignments', schema=None) as batch_op:
        batch_op.add_column(sa.Column('assignment_type', sa.String(length=30), server_default='One-to-one', nullable=False))
        batch_op.add_column(sa.Column('overlap_override_reason', sa.Text(), nullable=True))
        batch_op.add_column(sa.Column('overlap_approved_by_id', sa.Integer(), nullable=True))
        batch_op.create_unique_constraint('uq_buddy_assignment_exact', ['project_id', 'buddy_user_id', 'exchange_student_id', 'start_date'])
        batch_op.create_check_constraint('ck_buddy_assignment_dates', 'end_date >= start_date')
        batch_op.create_foreign_key('fk_buddy_overlap_approver', 'users', ['overlap_approved_by_id'], ['id'], ondelete='SET NULL')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('buddy_assignments', schema=None) as batch_op:
        batch_op.drop_constraint('fk_buddy_overlap_approver', type_='foreignkey')
        batch_op.drop_constraint('ck_buddy_assignment_dates', type_='check')
        batch_op.drop_constraint('uq_buddy_assignment_exact', type_='unique')
        batch_op.drop_column('overlap_approved_by_id')
        batch_op.drop_column('overlap_override_reason')
        batch_op.drop_column('assignment_type')

    # ### end Alembic commands ###
